[package]
name = "sqruff-sqlinference"
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqruff-lib = { version = "0.17.0", path = "../lib" }
