[workspace.package]
version = "0.9.0"
edition = "2021"
license = "Apache-2.0"

[workspace]
members = ["crates/lib", "crates/cli", "crates/lsp", "crates/sqlinference"]
resolver = "2"

# https://github.com/rustwasm/wasm-bindgen/issues/3451#issuecomment-1562982835
[profile.dev]
opt-level = "s"
