[package]
name = "sqruff"
description = "A high-speed SQL linter."
version = "0.1.4"
edition = "2021"
license = "MIT"

[[test]]
name = "ui"
harness = false

[dependencies]
sqruff-lib = { version = "0.1.4", path = "../lib" }
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
ui_test = "0.22"
