[package]
name = "sqruff"
description = "A high-speed SQL linter."
version = "0.4.7"
edition = "2021"
license = "Apache-2.0"
default-run = "sqruff"

[[test]]
name = "ui"
harness = false

[features]
jemalloc = ["jemallocator"]

[dependencies]
sqruff-lib = { version = "0.4.7", path = "../lib" }
clap = { version = "4", features = ["derive"] }
console = "0.15.8"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5", package = "tikv-jemallocator", optional = true }

[dev-dependencies]
ui_test = "0.22"
