[package]
name = "sqruff"
description = "A high-speed SQL linter."
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "sqruff"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"
bench = false

[[test]]
name = "ui"
harness = false

[features]
jemalloc = ["jemallocator"]
codegen-docs = ["clap-markdown", "minijinja", "serde"]

[dependencies]
sqruff-lib = { version = "0.9", path = "../lib" }
lsp = { version = "*", package = "sqruff-lsp", path = "../lsp" }
clap = { version = "4", features = ["derive"] }
console = "0.15.8"

# Codegen dependencies
clap-markdown = { version = "0.1.4", optional = true }
minijinja= { version="2.0.2" , optional = true }
serde = { version = "1.0.204", features = ["derive"], optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5", package = "tikv-jemallocator", optional = true }

[dev-dependencies]
ui_test = "0.23"
