[package]
name = "sqruff"
description = "A high-speed SQL linter."
version = "0.7.6"
edition = "2021"
license = "Apache-2.0"
default-run = "sqruff"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"
bench = false

[[test]]
name = "ui"
harness = false

[features]
jemalloc = ["jemallocator"]
codegen-docs = ["clap-markdown"]

[dependencies]
sqruff-lib = { version = "0.7.0", path = "../lib" }
lsp = { version = "*", package = "sqruff-lsp", path = "../lsp" }
clap = { version = "4", features = ["derive"] }
console = "0.15.8"
clap-markdown = { version = "0.1.4", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.5", package = "tikv-jemallocator", optional = true }

[dev-dependencies]
ui_test = "0.23"
