[build-system]
requires = ["maturin>=0.14,<0.15"] 
build-backend = "maturin" 

[project]
name = "sqruff" 
description = "A SQL linter written in rust." 
requires-python = ">=3.7" 

[tool.maturin]
bindings = "bin" 
strip = true 
