[build-system]
requires = ["maturin>=1.8"]
build-backend = "maturin" 

[project]
name = "sqruff" 
version = "0.24.2"
description = "A SQL linter written in rust." 
requires-python = ">=3.9" 

[tool.maturin]
bindings = "bin" 
strip = true 
