[build-system]
requires = ["maturin>=1.0"] 
build-backend = "maturin" 

[project]
name = "sqruff" 
version = "0.21.12"
description = "A SQL linter written in rust." 
requires-python = ">=3.9" 

[tool.maturin]
bindings = "bin" 
strip = true 
