[package]
name = "sqruff-lib-core"
description = "Core library that underpins the sqruff library."
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
serde = ["dep:serde"]
stringify = ["dep:serde_yaml", "serde"]

[dependencies]
smol_str = "0.3.1"
ahash = { version = "0.8.11", features = ["compile-time-rng", "serde"] }
strum = "0.26.3"
indexmap = "2.5.0"
strum_macros = "0.26.4"
nohash-hasher = "0.2.0"
itertools = "0.13.0"
fancy-regex = "0.14.0"
pretty_assertions = "1.4.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_yaml = { version = "0.9.34", optional = true }
rustc-hash = "2.0.0"
sptr = "0.3.2"
slyce = "0.3.1"
enum_dispatch = "0.3.13"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
