on:
  pull_request:
name: codegen-docs
env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
jobs:
  codegen-docs:
    name: codegen-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: env GITHUB_ACTIONS=false cargo r -F codegen-docs
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          push_options: "--force"
  codegen-check:
    name: codegen-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: env GITHUB_ACTIONS=false cargo r --bin sqruff -F codegen-docs
      - run: git diff --quiet || exit 1
