on:
  pull_request:
name: codegen-docs
jobs:
  codegen-docs:
    name: codegen-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo r -F codegen-docs > options.md
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          push_options: '--force'
